# Usando uma imagem oficial do Python
FROM python:3.11-slim

# Definindo o diretório de trabalho
WORKDIR /app

RUN pip install --upgrade pip setuptools wheel

# Copiando todos os arquivos do diretório para dentro do container
COPY requirements.txt requirements.txt
# Instalando dependências
RUN pip install --no-cache-dir -r requirements.txt

# Definindo variável de ambiente para garantir que o Python reconheça os módulos
ENV PYTHONPATH=/app

# Comando padrão de execução
CMD ["python", "appAPI.py"]
