[project]
name = "6-01"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "crewai>=0.117.1",
    "crewai-tools>=0.43.0",
    "dotenv>=0.9.9",
    "evolutionapi>=0.1.1",
    "pandas>=2.2.3",
    "streamlit>=1.44.1",
]
