[project]
name = "5-02"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "evolutionapi>=0.1.1",
    "flask>=3.1.0",
    "python-dotenv>=1.1.0",
    "streamlit>=1.44.1",
]
